from enum import StrEnum


class MissionType(StrEnum):
    STRIKE = "STRIKE"
    SEAD = "SEAD"  # suppression of enemy air defences
    DCA = "DCA"  # defensive counter-air (combat air patrol)


class TargetClass(StrEnum):
    AIRFIELD = "AIRFIELD"
    RADAR = "RADAR"
    SAM = "SAM"
    BRIDGE = "BRIDGE"
    DEPOT = "DEPOT"
    COMMAND = "COMMAND"
    ARMOUR = "ARMOUR"
    MOBILE = "MOBILE"  # mobile launcher or other relocatable target
    CAP_STATION = "CAP_STATION"


class WeaponKind(StrEnum):
    LGB = "LGB"  # laser-guided: needs a clear line of sight to the target
    GPS = "GPS"  # satellite-guided: all-weather, poor against moving targets
    STANDOFF = "STANDOFF"  # cruise missile: long release range, scarce
    ARM = "ARM"  # anti-radiation missile for SEAD
    AAM = "AAM"  # air-to-air missile for DCA
    UNGUIDED = "UNGUIDED"


class AircraftStatus(StrEnum):
    SERVICEABLE = "SERVICEABLE"
    UNSERVICEABLE = "UNSERVICEABLE"


class BaseStatus(StrEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class WeatherCondition(StrEnum):
    CLEAR = "CLEAR"
    CLOUD = "CLOUD"  # low cloud: laser and visual weapons unusable
    STORM = "STORM"  # no-go: no flying through it, no launch or recovery under it


class SourceSystem(StrEnum):
    MAINTENANCE = "MAINTENANCE"
    CREW = "CREW"
    ARMAMENT = "ARMAMENT"
    AIRSPACE = "AIRSPACE"
    MET = "MET"
    INTEL = "INTEL"
    OPS = "OPS"


class MissionOrigin(StrEnum):
    ATO = "ATO"  # from the commander's prioritised task list
    TST = "TST"  # time-sensitive target raised during execution
    AUTO_SEAD = "AUTO_SEAD"  # generated by the system for a newly detected SAM


class PackageStatus(StrEnum):
    PLANNED = "PLANNED"
    COMMITTED = "COMMITTED"  # inside the arming lead time
    AIRBORNE = "AIRBORNE"
    COMPLETE = "COMPLETE"


class ChangeKind(StrEnum):
    ADDED = "ADDED"
    REMOVED = "REMOVED"
    REASSIGNED = "REASSIGNED"
    RETIMED = "RETIMED"


class RejectReason(StrEnum):
    """Why a candidate (aircraft, loadout) for a mission was ruled out before solving."""

    AIRCRAFT_UNSERVICEABLE = "AIRCRAFT_UNSERVICEABLE"
    SERVICEABILITY_RISK = "SERVICEABILITY_RISK"
    BASE_UNAVAILABLE = "BASE_UNAVAILABLE"
    ROLE_MISMATCH = "ROLE_MISMATCH"
    NOT_NIGHT_CAPABLE = "NOT_NIGHT_CAPABLE"
    NO_SUITABLE_WEAPON = "NO_SUITABLE_WEAPON"
    NO_WEAPON_STOCK = "NO_WEAPON_STOCK"
    TARGET_WEATHER = "TARGET_WEATHER"
    ROUTE_BLOCKED = "ROUTE_BLOCKED"
    OUT_OF_RANGE = "OUT_OF_RANGE"
    TIME_WINDOW = "TIME_WINDOW"
    MAINTENANCE_DUE = "MAINTENANCE_DUE"
    NO_QUALIFIED_CREW = "NO_QUALIFIED_CREW"
